# GAE runtime and environment
runtime: nodejs12
env: standard

# GAE instance class
instance_class: F1

# Environment variables
service: default

# Autoscaling settings
automatic_scaling:
  max_instances: 1

# env variables
env_variables:
  PORT: 8080

# GAE start command
entrypoint: "npm run serve"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
