name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - prod
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - run: npm run build
